// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDspXc03g2dW8JKYtRYvtMAXZOkbfMr6TM',
    appId: '1:849170063014:web:175a44666cbe35027f1e67',
    messagingSenderId: '849170063014',
    projectId: 'app-mesero',
    authDomain: 'app-mesero.firebaseapp.com',
    storageBucket: 'app-mesero.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0qxEDK7s30anv4gjLBUfe0WhPZ2qtdmk',
    appId: '1:849170063014:android:51b23342b323442a7f1e67',
    messagingSenderId: '849170063014',
    projectId: 'app-mesero',
    storageBucket: 'app-mesero.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDspXc03g2dW8JKYtRYvtMAXZOkbfMr6TM',
    appId: '1:849170063014:web:b22376d562dccd607f1e67',
    messagingSenderId: '849170063014',
    projectId: 'app-mesero',
    authDomain: 'app-mesero.firebaseapp.com',
    storageBucket: 'app-mesero.firebasestorage.app',
  );
}
